name: 'Gitleaks Scan Action'
description: 'Scan repository for secrets using Gitleaks'
inputs:
  repository:
    description: 'The name of the repository'
    required: true
  ref:
    description: 'The branch or ref to scan'
    required: true
  github_token:
    description: 'GitHub token'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        repository: ${{ inputs.repository }}
        ref: ${{ inputs.ref }}
    - name: Run Gitleaks Scan
      uses: gitleaks/gitleaks-action@v2
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
